// Game data. r: region key, y: release, t: blurb.
// icon: URL/path to the game's icon image (null = initials badge is shown).
// hero: URL/path to a hero image for the detail card (null = placeholder strip).
const ICO = "assets/icons/";
const GAMES = [
  // MICRO
  {n:"osu!", r:"micro", icon:ICO+"osu.png", hero:null, y:"2007", t:"Click circles to the beat with surgical precision."},
  {n:"Geometry Dash", r:"micro", icon:ICO+"geometry-dash.png", hero:null, y:"2013", t:"One-touch rhythm platforming, memorized to the frame."},
  {n:"Tetris", r:"micro", icon:ICO+"tetris.png", hero:null, y:"1984", t:"Stack falling blocks faster than you can think."},
  {n:"Beat Saber", r:"micro", icon:ICO+"beat-saber.png", hero:null, y:"2018", t:"Slice blocks to the beat in VR."},
  {n:"Flappy Bird", r:"micro", icon:ICO+"flappy-bird.png", hero:null, y:"2013", t:"One tap, one pipe, infinite rage."},
  {n:"Crossy Road", r:"micro", icon:ICO+"crossy-road.png", hero:null, y:"2014", t:"Endless road crossing on split-second hops."},
  {n:"Super Meat Boy", r:"micro", icon:ICO+"super-meat-boy.png", hero:null, y:"2010", t:"Brutal precision platforming, one death per second."},
  {n:"Subway Surfers", r:"micro", icon:ICO+"subway-surfers.png", hero:null, y:"2012", t:"Endless runner reflex swipes."},
  {n:"Taiko no Tatsujin", r:"micro", icon:ICO+"taiko-no-tatsujin.png", hero:null, y:"2001", t:"Drum to the beat, taiko style."},
  {n:"Friday Night Funkin'", r:"micro", icon:ICO+"friday-night-funkin.png", hero:null, y:"2020", t:"Rhythm battles against your girlfriend's dad."},
  {n:"A Dance of Fire and Ice", r:"micro", icon:ICO+"a-dance-of-fire-and-ice.png", hero:null, y:"2019", t:"One-button rhythm, zero forgiveness."},
  {n:"Super Mario Maker", r:"micro", icon:ICO+"super-mario-maker.png", hero:null, y:"2015", t:"Build and beat pixel-perfect Mario levels."},
  {n:"CS2 Surf", r:"micro", icon:ICO+"cs2-surf.png", hero:null, y:"2023", t:"Ride ramps on pure air-strafe control."},
  {n:"Aim Lab", r:"micro", icon:ICO+"aim-lab.png", hero:null, y:"2021", t:"Pure aim training, nothing else."},
  {n:"Devil Daggers", r:"micro", icon:ICO+"devil-daggers.png", hero:null, y:"2016", t:"Survive one arena with perfect aim, forever."},
  {n:"TypeRacer", r:"micro", icon:ICO+"typeracer.png", hero:null, y:"2008", t:"Competitive typing at raw words per minute."},
  {n:"Super Hexagon", r:"micro", icon:ICO+"super-hexagon.png", hero:null, y:"2012", t:"Dodge walls for sixty impossible seconds."},
  {n:"Clone Hero", r:"micro", icon:ICO+"clone-hero.png", hero:null, y:"2017", t:"Plastic guitar shredding at full speed."},
  {n:"Muse Dash", r:"micro", icon:ICO+"muse-dash.png", hero:null, y:"2018", t:"Two-lane rhythm brawling."},
  {n:"F-Zero GX", r:"micro", icon:ICO+"f-zero-gx.png", hero:null, y:"2003", t:"Anti-gravity racing with zero assists."},
  {n:"QWOP", r:"micro", icon:ICO+"qwop.png", hero:null, y:"2008", t:"Four keys, two legs, no dignity."},
  {n:"StepMania", r:"micro", icon:ICO+"stepmania.png", hero:null, y:"2001", t:"Arrow-perfect dance machine at home."},
  {n:"Rhythm Heaven", r:"micro", icon:ICO+"rhythm-heaven.png", hero:null, y:"2006", t:"Nintendo's strictest metronome."},
  {n:"Ghostrunner", r:"micro", icon:ICO+"ghostrunner.png", hero:null, y:"2020", t:"One-hit katana parkour."},
  {n:"Half Sword", r:"micro", icon:ICO+"half-sword.png", hero:null, y:"2024", t:"Physics-driven medieval duels."},
  {n:"Hot Lava", r:"micro", icon:ICO+"hot-lava.png", hero:null, y:"2019", t:"The floor is finally lava."},
  {n:"I Wanna Be the Guy", r:"micro", icon:ICO+"i-wanna-be-the-guy.png", hero:null, y:"2007", t:"Every pixel wants you dead."},
  {n:"Dark Roll", r:"micro", icon:ICO+"dark-roll.png", hero:null, y:"2024", t:"Cursed dice on the run."},
  // MICRO + MACRO
  {n:"Elden Ring", r:"micro-macro", icon:ICO+"elden-ring.png", hero:null, y:"2022", t:"Master the combat, then master the build."},
  {n:"Hades", r:"micro-macro", icon:ICO+"hades.png", hero:null, y:"2020", t:"Roguelite dashes meet boon-stacking strategy."},
  {n:"Hollow Knight: Silksong", r:"micro-macro", icon:ICO+"hollow-knight-silksong.png", hero:null, y:"2025", t:"Needle-precise combat across a hostile kingdom."},
  {n:"Portal 2", r:"micro-macro", icon:ICO+"portal-2.png", hero:null, y:"2011", t:"Momentum puzzles with flawless execution."},
  {n:"Celeste", r:"micro-macro", icon:ICO+"celeste.png", hero:null, y:"2018", t:"Dash-perfect platforming up a mountain of routes."},
  {n:"Zelda: Breath of the Wild", r:"micro-macro", icon:ICO+"zelda-botw.png", hero:null, y:"2017", t:"Open-world routing meets shrine execution."},
  {n:"Super Mario 64", r:"micro-macro", icon:ICO+"super-mario-64.png", hero:null, y:"1996", t:"Movement tech and star-routing heaven."},
  {n:"Cuphead", r:"micro-macro", icon:ICO+"cuphead.png", hero:null, y:"2017", t:"Pattern-perfect boss runs, learned by heart."},
  {n:"Monster Hunter", r:"micro-macro", icon:ICO+"monster-hunter.png", hero:null, y:"2004", t:"Learn the monster, craft the counter."},
  {n:"Terraria", r:"micro-macro", icon:ICO+"terraria.png", hero:null, y:"2011", t:"Boss execution atop deep progression planning."},
  {n:"8 Ball Pool", r:"micro-macro", icon:ICO+"8-ball-pool.png", hero:null, y:"2010", t:"Cue precision plus table control."},
  {n:"Rubik's Cube", r:"micro-macro", icon:ICO+"rubiks-cube.png", hero:null, y:"1974", t:"Finger speed on memorized algorithms."},
  {n:"Jump King", r:"micro-macro", icon:ICO+"jump-king.png", hero:null, y:"2019", t:"Charge every jump, pay for every mistake."},
  {n:"Getting Over It", r:"micro-macro", icon:ICO+"getting-over-it.png", hero:null, y:"2017", t:"One hammer, one pot, total control."},
  {n:"The Forest", r:"micro-macro", icon:ICO+"the-forest.png", hero:null, y:"2018", t:"Survive, build, and fight smart."},
  {n:"Noita", r:"micro-macro", icon:ICO+"noita.png", hero:null, y:"2020", t:"Every pixel simulated, every wand a build."},
  {n:"Mega Man", r:"micro-macro", icon:null, hero:null, y:"1987", t:"Pattern platforming with boss-order strategy."},
  {n:"Furi", r:"micro-macro", icon:null, hero:null, y:"2016", t:"Duel bosses with parry-perfect timing."},
  {n:"Doom", r:"micro-macro", icon:ICO+"doom.png", hero:null, y:"1993", t:"Rip and tear with weapon-swap routing."},
  {n:"Hades II", r:"micro-macro", icon:ICO+"hades-ii.png", hero:null, y:"2024", t:"Witchcraft dashes and deeper boon math."},
  {n:"Vampire Survivors", r:"micro-macro", icon:ICO+"vampire-survivors.png", hero:null, y:"2022", t:"Dodge the horde while the build compounds."},
  {n:"Dead Cells", r:"micro-macro", icon:ICO+"dead-cells.png", hero:null, y:"2018", t:"Roguelite combat at full sprint."},
  {n:"Devil May Cry 5", r:"micro-macro", icon:ICO+"devil-may-cry-5.png", hero:null, y:"2019", t:"Style meters reward lab-tested combos."},
  {n:"Ultrakill", r:"micro-macro", icon:ICO+"ultrakill.png", hero:null, y:"2020", t:"Blood is fuel; movement is math."},
  // MACRO
  {n:"Factorio", r:"macro", icon:ICO+"factorio.png", hero:null, y:"2020", t:"The factory must grow, optimally."},
  {n:"Poly Bridge", r:"macro", icon:ICO+"poly-bridge.png", hero:null, y:"2016", t:"Budget bridges under real physics."},
  {n:"shapez", r:"macro", icon:ICO+"shapez.png", hero:null, y:"2020", t:"Infinite factory shape routing."},
  {n:"Kerbal Space Program", r:"macro", icon:ICO+"kerbal-space-program.png", hero:null, y:"2015", t:"Orbital mechanics by trial and math."},
  {n:"Oxygen Not Included", r:"macro", icon:ICO+"oxygen-not-included.png", hero:null, y:"2019", t:"Thermodynamics as colony management."},
  {n:"Mini Motorways", r:"macro", icon:ICO+"mini-motorways.png", hero:null, y:"2021", t:"Road networks under growing pressure."},
  {n:"Dwarf Fortress", r:"macro", icon:ICO+"dwarf-fortress.png", hero:null, y:"2006", t:"Losing is fun, planning is survival."},
  {n:"7 Billion Humans", r:"macro", icon:ICO+"7-billion-humans.png", hero:null, y:"2018", t:"Program a crowd to solve puzzles."},
  {n:"Cities: Skylines", r:"macro", icon:ICO+"cities-skylines.png", hero:null, y:"2015", t:"Traffic flow is the real boss."},
  {n:"Opus Magnum", r:"macro", icon:ICO+"opus-magnum.png", hero:null, y:"2017", t:"Elegant machines, optimized three ways."},
  {n:"Stardew Valley", r:"macro", icon:ICO+"stardew-valley.png", hero:null, y:"2016", t:"Farm layouts, crop math, day routing."},
  {n:"Cookie Clicker", r:"macro", icon:ICO+"cookie-clicker.png", hero:null, y:"2013", t:"Idle optimization all the way down."},
  {n:"Football Manager 2026", r:"macro", icon:ICO+"football-manager-2026.png", hero:null, y:"2025", t:"Spreadsheet football at its purest."},
  {n:"Europa Universalis IV", r:"macro", icon:ICO+"europa-universalis-iv.png", hero:null, y:"2013", t:"Map-painting grand strategy."},
  {n:"Crusader Kings", r:"macro", icon:ICO+"crusader-kings.png", hero:null, y:"2020", t:"Dynasty scheming across centuries."},
  {n:"Slime Rancher", r:"macro", icon:null, hero:null, y:"2017", t:"Ranch logistics with adorable slimes."},
  {n:"Papers, Please", r:"macro", icon:null, hero:null, y:"2013", t:"Bureaucracy under moral pressure."},
  {n:"Connect 4", r:"macro", icon:ICO+"connect-4.png", hero:null, y:"1974", t:"Solved, but not by you."},
  {n:"Tic-Tac-Toe", r:"macro", icon:ICO+"tic-tac-toe.png", hero:null, y:"antiquity", t:"The first game you ever solved."},
  {n:"Sudoku", r:"macro", icon:ICO+"sudoku.png", hero:null, y:"1979", t:"Pure constraint logic."},
  {n:"Against the Storm", r:"macro", icon:ICO+"against-the-storm.png", hero:null, y:"2023", t:"Build settlements faster than the rain."},
  {n:"RimWorld", r:"macro", icon:ICO+"rimworld.png", hero:null, y:"2018", t:"Colony stories run on spreadsheets."},
  {n:"Victoria 3", r:"macro", icon:ICO+"victoria-3.png", hero:null, y:"2022", t:"The economy is the war."},
  {n:"SimCity", r:"macro", icon:ICO+"simcity.png", hero:null, y:"2013", t:"Zoning dreams, traffic regrets."},
  {n:"Satisfactory", r:"macro", icon:ICO+"satisfactory.png", hero:null, y:"2024", t:"First-person factory sprawl."},
  {n:"AdVenture Capitalist", r:"macro", icon:ICO+"adventure-capitalist.png", hero:null, y:"2014", t:"Money that hires money."},
  {n:"Clicker Heroes", r:"macro", icon:ICO+"clicker-heroes.png", hero:null, y:"2014", t:"Numbers go up, optimally."},
  {n:"Jigsaw Puzzles", r:"macro", icon:ICO+"jigsaw-puzzles.png", hero:null, y:"~1760", t:"Edges first. Always edges first."},
  // MICRO + MESO
  {n:"Super Smash Bros", r:"micro-meso", icon:ICO+"super-smash-bros.png", hero:null, y:"1999", t:"Reads and tech skill at 60 frames."},
  {n:"Street Fighter", r:"micro-meso", icon:ICO+"street-fighter.png", hero:null, y:"1987", t:"Footsies, frames, and mind games."},
  {n:"Tekken 8", r:"micro-meso", icon:ICO+"tekken-8.png", hero:null, y:"2024", t:"3D movement and 50/50 guesses."},
  {n:"Mortal Kombat", r:"micro-meso", icon:ICO+"mortal-kombat.png", hero:null, y:"1992", t:"Brutal strings and conditioning."},
  {n:"Guilty Gear", r:"micro-meso", icon:ICO+"guilty-gear.png", hero:null, y:"1998", t:"Anime pressure and hard reads."},
  {n:"Dragon Ball FighterZ", r:"micro-meso", icon:ICO+"dragon-ball-fighterz.png", hero:null, y:"2018", t:"Tag combos at blistering speed."},
  {n:"Brawlhalla", r:"micro-meso", icon:ICO+"brawlhalla.png", hero:null, y:"2017", t:"Platform-fighting reads, free to play."},
  {n:"For Honor", r:"micro-meso", icon:ICO+"for-honor.png", hero:null, y:"2017", t:"Directional mind games with swords."},
  {n:"Chivalry 2", r:"micro-meso", icon:ICO+"chivalry-2.png", hero:null, y:"2021", t:"Medieval swings, feints, and drags."},
  {n:"Mordhau", r:"micro-meso", icon:ICO+"mordhau.png", hero:null, y:"2019", t:"Swordplay where feints win fights."},
  {n:"Quake", r:"micro-meso", icon:ICO+"quake.png", hero:null, y:"1996", t:"Duels of aim and item timing."},
  {n:"Tetris 99", r:"micro-meso", icon:ICO+"tetris-99.png", hero:null, y:"2019", t:"Battle-royale stacking under fire."},
  {n:"Fall Guys", r:"micro-meso", icon:ICO+"fall-guys.png", hero:null, y:"2020", t:"Chaos platforming against 59 others."},
  {n:"Gang Beasts", r:"micro-meso", icon:ICO+"gang-beasts.png", hero:null, y:"2017", t:"Wobbly grapples, real betrayals."},
  {n:"Party Animals", r:"micro-meso", icon:ICO+"party-animals.png", hero:null, y:"2023", t:"Physics brawls with friends."},
  {n:"Mario Kart", r:"micro-meso", icon:ICO+"mario-kart.png", hero:null, y:"1992", t:"Items, drift, and rubber-band reads."},
  {n:"2XKO", r:"micro-meso", icon:ICO+"2xko.png", hero:null, y:"2025", t:"Riot's tag-team mind games."},
  // CENTER
  {n:"Counter-Strike 2", r:"center", icon:ICO+"counter-strike-2.png", hero:null, y:"2023", t:"Aim, utility, economy, and reads."},
  {n:"Valorant", r:"center", icon:ICO+"valorant.png", hero:null, y:"2020", t:"Tactical aim with ability layers."},
  {n:"League of Legends", r:"center", icon:ICO+"league-of-legends.png", hero:null, y:"2009", t:"Lane mechanics to map strategy."},
  {n:"Dota 2", r:"center", icon:ICO+"dota-2.png", hero:null, y:"2013", t:"The deepest draft in esports."},
  {n:"Overwatch", r:"center", icon:ICO+"overwatch.png", hero:null, y:"2016", t:"Hero swaps and ult economies."},
  {n:"Apex Legends", r:"center", icon:ICO+"apex-legends.png", hero:null, y:"2019", t:"Movement gunplay and rotations."},
  {n:"Rocket League", r:"center", icon:ICO+"rocket-league.png", hero:null, y:"2015", t:"Car soccer: mechanics, reads, rotation."},
  {n:"Fortnite", r:"center", icon:ICO+"fortnite.png", hero:null, y:"2017", t:"Build fights and zone strategy."},
  {n:"Rainbow Six Siege", r:"center", icon:ICO+"rainbow-six-siege.png", hero:null, y:"2015", t:"Intel, angles, and one-taps."},
  {n:"StarCraft II", r:"center", icon:ICO+"starcraft-ii.png", hero:null, y:"2010", t:"APM meets build orders."},
  {n:"Halo Infinite", r:"center", icon:ICO+"halo-infinite.png", hero:null, y:"2021", t:"Arena shooting with weapon control."},
  {n:"The Finals", r:"center", icon:ICO+"the-finals.png", hero:null, y:"2023", t:"Destructible arenas, cash-out chaos."},
  {n:"PUBG", r:"center", icon:ICO+"pubg.png", hero:null, y:"2017", t:"The battle-royale blueprint."},
  {n:"Dead by Daylight", r:"center", icon:ICO+"dead-by-daylight.png", hero:null, y:"2016", t:"Asymmetric cat and mouse."},
  {n:"CoD Modern Warfare", r:"center", icon:ICO+"cod-modern-warfare.png", hero:null, y:"2019", t:"Gunskill, spawns, and streaks."},
  {n:"Marvel Rivals", r:"center", icon:ICO+"marvel-rivals.png", hero:null, y:"2024", t:"Hero shooter, team synergy."},
  {n:"Team Fortress 2", r:"center", icon:ICO+"team-fortress-2.png", hero:null, y:"2007", t:"Nine classes, endless meta."},
  {n:"SMITE", r:"center", icon:ICO+"smite.png", hero:null, y:"2014", t:"A MOBA in third person."},
  {n:"Battlefield", r:"center", icon:ICO+"battlefield.png", hero:null, y:"2002", t:"Combined arms at scale."},
  {n:"Destiny 2", r:"center", icon:ICO+"destiny-2.png", hero:null, y:"2017", t:"Gunfeel plus loadout math."},
  {n:"Rust", r:"center", icon:ICO+"rust.png", hero:null, y:"2018", t:"Aim, alliances, and base design."},
  {n:"Deadlock", r:"center", icon:ICO+"deadlock.png", hero:null, y:"2024", t:"Valve's MOBA-shooter hybrid."},
  {n:"Diablo IV", r:"center", icon:ICO+"diablo-iv.png", hero:null, y:"2023", t:"Builds, seasons, and pushing."},
  {n:"Naraka: Bladepoint", r:"center", icon:ICO+"naraka-bladepoint.png", hero:null, y:"2021", t:"Melee royale with parries."},
  {n:"Warframe", r:"center", icon:ICO+"warframe.png", hero:null, y:"2013", t:"Space-ninja builds and movement."},
  {n:"World of Warcraft", r:"center", icon:ICO+"world-of-warcraft.png", hero:null, y:"2004", t:"Rotations, comps, and prep."},
  {n:"Delta Force", r:"center", icon:ICO+"delta-force.png", hero:null, y:"2024", t:"Tactical extraction warfare."},
  {n:"ARC Raiders", r:"center", icon:ICO+"arc-raiders.png", hero:null, y:"2025", t:"Co-op extraction under machine fire."},
  {n:"EA Sports FC", r:"center", icon:ICO+"ea-sports-fc.png", hero:null, y:"2023", t:"Skill moves and squad meta."},
  {n:"Trackmania", r:"center", icon:ICO+"trackmania.png", hero:null, y:"2020", t:"Millisecond racing lines."},
  {n:"Clash Royale", r:"center", icon:ICO+"clash-royale.png", hero:null, y:"2016", t:"Elixir trades and tower reads."},
  {n:"Escape from Tarkov", r:"center", icon:ICO+"escape-from-tarkov.png", hero:null, y:"2017", t:"Gear fear and map knowledge."},
  {n:"ARK: Survival Evolved", r:"center", icon:ICO+"ark.png", hero:null, y:"2017", t:"Tame dinos, out-scheme tribes."},
  {n:"MCSR Ranked", r:"center", icon:ICO+"mcsr-ranked.png", hero:null, y:"2022", t:"Minecraft speedruns, head to head."},
  // MESO + MACRO
  {n:"Hearthstone", r:"meso-macro", icon:ICO+"hearthstone.png", hero:null, y:"2014", t:"Card value and bluffing the RNG."},
  {n:"Teamfight Tactics", r:"meso-macro", icon:ICO+"teamfight-tactics.png", hero:null, y:"2019", t:"Economy, scouting, positioning."},
  {n:"Balatro", r:"meso-macro", icon:ICO+"balatro.png", hero:null, y:"2024", t:"Poker hands turned roguelike math."},
  {n:"Slay the Spire 2", r:"meso-macro", icon:ICO+"slay-the-spire-2.png", hero:null, y:"2025", t:"Deck math against known odds."},
  {n:"Pokémon VGC", r:"meso-macro", icon:ICO+"pokemon-vgc.png", hero:null, y:"2008", t:"Team building and prediction."},
  {n:"MTG Arena", r:"meso-macro", icon:ICO+"mtg-arena.png", hero:null, y:"2019", t:"The deepest card pool, digital."},
  {n:"Chess", r:"meso-macro", icon:ICO+"chess.png", hero:null, y:"~600", t:"Perfect information, imperfect humans."},
  {n:"Civilization VI", r:"meso-macro", icon:ICO+"civilization-vi.png", hero:null, y:"2016", t:"One more turn of grand planning."},
  {n:"Poker", r:"meso-macro", icon:ICO+"poker.png", hero:null, y:"1800s", t:"Probability wrapped in psychology."},
  {n:"Risk", r:"meso-macro", icon:ICO+"risk.png", hero:null, y:"1957", t:"Dice, diplomacy, and betrayal."},
  {n:"Catan", r:"meso-macro", icon:ICO+"catan.png", hero:null, y:"1995", t:"Trades, odds, and table politics."},
  {n:"Battleship", r:"meso-macro", icon:ICO+"battleship.png", hero:null, y:"1967", t:"Hidden information, gridded."},
  {n:"Monopoly", r:"meso-macro", icon:ICO+"monopoly.png", hero:null, y:"1935", t:"Trades, hotels, and grudges."},
  {n:"Super Auto Pets", r:"meso-macro", icon:ICO+"super-auto-pets.png", hero:null, y:"2021", t:"Auto-battler team comps at your pace."},
  {n:"Phasmophobia", r:"meso-macro", icon:ICO+"phasmophobia.png", hero:null, y:"2020", t:"Deduce the ghost before it hunts."},
  // MESO
  {n:"Among Us", r:"meso", icon:ICO+"among-us.png", hero:null, y:"2018", t:"Lie to your friends in space."},
  {n:"Goose Goose Duck", r:"meso", icon:ICO+"goose-goose-duck.png", hero:null, y:"2021", t:"Social deduction with waterfowl."},
  {n:"Liar's Bar", r:"meso", icon:ICO+"liars-bar.png", hero:null, y:"2024", t:"Bluff or drink the poison."},
  {n:"Codenames", r:"meso", icon:ICO+"codenames.png", hero:null, y:"2015", t:"One word, many minds."},
  {n:"Rock Paper Scissors", r:"meso", icon:ICO+"rock-paper-scissors.png", hero:null, y:"antiquity", t:"The purest mind game."},
  {n:"SpyParty", r:"meso", icon:ICO+"spyparty.png", hero:null, y:"2018", t:"One spy, one sniper, pure reads."},
  {n:"Secret Neighbor", r:"meso", icon:ICO+"secret-neighbor.png", hero:null, y:"2019", t:"Social deduction in the neighbor's house."},
  {n:"Guess Who?", r:"meso", icon:ICO+"guess-who.png", hero:null, y:"1979", t:"Binary-search a face."},
  {n:"GTA Online", r:"meso", icon:ICO+"gta-online.png", hero:null, y:"2013", t:"Trust no lobby."},
  {n:"Werewolf Party", r:"meso", icon:ICO+"werewolf-party.png", hero:null, y:"1986", t:"The village lies at night."},
  {n:"The Stock Market", r:"meso", icon:ICO+"the-stock-market.png", hero:null, y:"1602", t:"The oldest PvP mind game."},
  {n:"Slot Machine", r:"meso", icon:ICO+"slot-machine.png", hero:null, y:"1895", t:"The house always wins."},
  {n:"Town of Salem", r:"meso", icon:ICO+"town-of-salem.png", hero:null, y:"2014", t:"Roles, lies, and lynch votes."},
  {n:"Blood on the Clocktower", r:"meso", icon:ICO+"blood-on-the-clocktower.png", hero:null, y:"2022", t:"Even the dead keep bluffing."},
  {n:"Mafia", r:"meso", icon:ICO+"mafia.png", hero:null, y:"1986", t:"The original parlor deception."},
  {n:"Coup", r:"meso", icon:ICO+"coup.png", hero:null, y:"2012", t:"Two cards, endless lies."},
  {n:"The Resistance: Avalon", r:"meso", icon:ICO+"avalon.png", hero:null, y:"2012", t:"Merlin knows. Don't be obvious."},
  {n:"Spyfall", r:"meso", icon:ICO+"spyfall.png", hero:null, y:"2014", t:"One player has no idea where they are."},
  {n:"Project Winter", r:"meso", icon:ICO+"project-winter.png", hero:null, y:"2019", t:"Survive the cold, doubt the rescue."},
  {n:"Liar's Dice", r:"meso", icon:ICO+"liars-dice.png", hero:null, y:"1800s", t:"Bid high, bluff higher."},
  {n:"Case Unboxing", r:"meso", icon:ICO+"case-unboxing.png", hero:null, y:"2013", t:"Gambling with extra steps."},
];
const REGIONS = {
  "micro": "Micro",
  "micro-macro": "Micro + Macro",
  "macro": "Macro",
  "micro-meso": "Micro + Meso",
  "center": "Micro + Meso + Macro",
  "meso-macro": "Meso + Macro",
  "meso": "Meso",
};
