// Game data. r: region key, y: release.
// icon: URL/path to the game's icon image (null = initials badge is shown).
// hero: URL/path to a hero image for the detail card (null = placeholder strip).
const ICO = "assets/icons/";
const GAMES = [
  // MICRO
  {n:"osu!", r:"micro", icon:ICO+"osu.png", hero:null, y:"2007"},
  {n:"Geometry Dash", r:"micro", icon:ICO+"geometry-dash.png", hero:null, y:"2013"},
  {n:"Tetris", r:"micro", icon:ICO+"tetris.png", hero:null, y:"1984"},
  {n:"Beat Saber", r:"micro", icon:ICO+"beat-saber.png", hero:null, y:"2018"},
  {n:"Flappy Bird", r:"micro", icon:ICO+"flappy-bird.png", hero:null, y:"2013"},
  {n:"Crossy Road", r:"micro", icon:ICO+"crossy-road.png", hero:null, y:"2014"},
  {n:"Super Meat Boy", r:"micro", icon:ICO+"super-meat-boy.png", hero:null, y:"2010"},
  {n:"Subway Surfers", r:"micro", icon:ICO+"subway-surfers.png", hero:null, y:"2012"},
  {n:"Taiko no Tatsujin", r:"micro", icon:ICO+"taiko-no-tatsujin.png", hero:null, y:"2001"},
  {n:"Friday Night Funkin'", r:"micro", icon:ICO+"friday-night-funkin.png", hero:null, y:"2020"},
  {n:"A Dance of Fire and Ice", r:"micro", icon:ICO+"a-dance-of-fire-and-ice.png", hero:null, y:"2019"},
  {n:"Super Mario Maker", r:"micro", icon:ICO+"super-mario-maker.png", hero:null, y:"2015"},
  {n:"CS2 Surf", r:"micro", icon:ICO+"cs2-surf.png", hero:null, y:"2023"},
  {n:"Aim Lab", r:"micro", icon:ICO+"aim-lab.png", hero:null, y:"2021"},
  {n:"Devil Daggers", r:"micro", icon:ICO+"devil-daggers.png", hero:null, y:"2016"},
  {n:"TypeRacer", r:"micro", icon:ICO+"typeracer.png", hero:null, y:"2008"},
  {n:"Super Hexagon", r:"micro", icon:ICO+"super-hexagon.png", hero:null, y:"2012"},
  {n:"Clone Hero", r:"micro", icon:ICO+"clone-hero.png", hero:null, y:"2017"},
  {n:"Muse Dash", r:"micro", icon:ICO+"muse-dash.png", hero:null, y:"2018"},
  {n:"F-Zero GX", r:"micro", icon:ICO+"f-zero-gx.png", hero:null, y:"2003"},
  {n:"QWOP", r:"micro", icon:ICO+"qwop.png", hero:null, y:"2008"},
  {n:"StepMania", r:"micro", icon:ICO+"stepmania.png", hero:null, y:"2001"},
  {n:"Rhythm Heaven", r:"micro", icon:ICO+"rhythm-heaven.png", hero:null, y:"2006"},
  {n:"Ghostrunner", r:"micro", icon:ICO+"ghostrunner.png", hero:null, y:"2020"},
  {n:"Half Sword", r:"micro", icon:ICO+"half-sword.png", hero:null, y:"2024"},
  {n:"Hot Lava", r:"micro", icon:ICO+"hot-lava.png", hero:null, y:"2019"},
  {n:"I Wanna Be the Guy", r:"micro", icon:ICO+"i-wanna-be-the-guy.png", hero:null, y:"2007"},
  {n:"Dark Roll", r:"micro", icon:ICO+"dark-roll.png", hero:null, y:"2024"},
  // MICRO + MACRO
  {n:"Elden Ring", r:"micro-macro", icon:ICO+"elden-ring.png", hero:null, y:"2022"},
  {n:"Hades", r:"micro-macro", icon:ICO+"hades.png", hero:null, y:"2020"},
  {n:"Hollow Knight: Silksong", r:"micro-macro", icon:ICO+"hollow-knight-silksong.png", hero:null, y:"2025"},
  {n:"Portal 2", r:"micro-macro", icon:ICO+"portal-2.png", hero:null, y:"2011"},
  {n:"Celeste", r:"micro-macro", icon:ICO+"celeste.png", hero:null, y:"2018"},
  {n:"Zelda: Breath of the Wild", r:"micro-macro", icon:ICO+"zelda-botw.png", hero:null, y:"2017"},
  {n:"Super Mario 64", r:"micro-macro", icon:ICO+"super-mario-64.png", hero:null, y:"1996"},
  {n:"Cuphead", r:"micro-macro", icon:ICO+"cuphead.png", hero:null, y:"2017"},
  {n:"Monster Hunter", r:"micro-macro", icon:ICO+"monster-hunter.png", hero:null, y:"2004"},
  {n:"Terraria", r:"micro-macro", icon:ICO+"terraria.png", hero:null, y:"2011"},
  {n:"8 Ball Pool", r:"micro-macro", icon:ICO+"8-ball-pool.png", hero:null, y:"2010"},
  {n:"Rubik's Cube", r:"micro-macro", icon:ICO+"rubiks-cube.png", hero:null, y:"1974"},
  {n:"Jump King", r:"micro-macro", icon:ICO+"jump-king.png", hero:null, y:"2019"},
  {n:"Getting Over It", r:"micro-macro", icon:ICO+"getting-over-it.png", hero:null, y:"2017"},
  {n:"The Forest", r:"micro-macro", icon:ICO+"the-forest.png", hero:null, y:"2018"},
  {n:"Noita", r:"micro-macro", icon:ICO+"noita.png", hero:null, y:"2020"},
  {n:"Mega Man", r:"micro-macro", icon:null, hero:null, y:"1987"},
  {n:"Furi", r:"micro-macro", icon:null, hero:null, y:"2016"},
  {n:"Doom", r:"micro-macro", icon:ICO+"doom.png", hero:null, y:"1993"},
  {n:"Hades II", r:"micro-macro", icon:ICO+"hades-ii.png", hero:null, y:"2024"},
  {n:"Vampire Survivors", r:"micro-macro", icon:ICO+"vampire-survivors.png", hero:null, y:"2022"},
  {n:"Dead Cells", r:"micro-macro", icon:ICO+"dead-cells.png", hero:null, y:"2018"},
  {n:"Devil May Cry 5", r:"micro-macro", icon:ICO+"devil-may-cry-5.png", hero:null, y:"2019"},
  {n:"Ultrakill", r:"micro-macro", icon:ICO+"ultrakill.png", hero:null, y:"2020"},
  // MACRO
  {n:"Factorio", r:"macro", icon:ICO+"factorio.png", hero:null, y:"2020"},
  {n:"Poly Bridge", r:"macro", icon:ICO+"poly-bridge.png", hero:null, y:"2016"},
  {n:"shapez", r:"macro", icon:ICO+"shapez.png", hero:null, y:"2020"},
  {n:"Kerbal Space Program", r:"macro", icon:ICO+"kerbal-space-program.png", hero:null, y:"2015"},
  {n:"Oxygen Not Included", r:"macro", icon:ICO+"oxygen-not-included.png", hero:null, y:"2019"},
  {n:"Mini Motorways", r:"macro", icon:ICO+"mini-motorways.png", hero:null, y:"2021"},
  {n:"Dwarf Fortress", r:"macro", icon:ICO+"dwarf-fortress.png", hero:null, y:"2006"},
  {n:"7 Billion Humans", r:"macro", icon:ICO+"7-billion-humans.png", hero:null, y:"2018"},
  {n:"Cities: Skylines", r:"macro", icon:ICO+"cities-skylines.png", hero:null, y:"2015"},
  {n:"Opus Magnum", r:"macro", icon:ICO+"opus-magnum.png", hero:null, y:"2017"},
  {n:"Stardew Valley", r:"macro", icon:ICO+"stardew-valley.png", hero:null, y:"2016"},
  {n:"Cookie Clicker", r:"macro", icon:ICO+"cookie-clicker.png", hero:null, y:"2013"},
  {n:"Football Manager 2026", r:"macro", icon:ICO+"football-manager-2026.png", hero:null, y:"2025"},
  {n:"Europa Universalis IV", r:"macro", icon:ICO+"europa-universalis-iv.png", hero:null, y:"2013"},
  {n:"Crusader Kings", r:"macro", icon:ICO+"crusader-kings.png", hero:null, y:"2020"},
  {n:"Slime Rancher", r:"macro", icon:null, hero:null, y:"2017"},
  {n:"Papers, Please", r:"macro", icon:null, hero:null, y:"2013"},
  {n:"Connect 4", r:"macro", icon:ICO+"connect-4.png", hero:null, y:"1974"},
  {n:"Tic-Tac-Toe", r:"macro", icon:ICO+"tic-tac-toe.png", hero:null, y:"antiquity"},
  {n:"Sudoku", r:"macro", icon:ICO+"sudoku.png", hero:null, y:"1979"},
  {n:"Against the Storm", r:"macro", icon:ICO+"against-the-storm.png", hero:null, y:"2023"},
  {n:"RimWorld", r:"macro", icon:ICO+"rimworld.png", hero:null, y:"2018"},
  {n:"Victoria 3", r:"macro", icon:ICO+"victoria-3.png", hero:null, y:"2022"},
  {n:"SimCity", r:"macro", icon:ICO+"simcity.png", hero:null, y:"2013"},
  {n:"Satisfactory", r:"macro", icon:ICO+"satisfactory.png", hero:null, y:"2024"},
  {n:"AdVenture Capitalist", r:"macro", icon:ICO+"adventure-capitalist.png", hero:null, y:"2014"},
  {n:"Clicker Heroes", r:"macro", icon:ICO+"clicker-heroes.png", hero:null, y:"2014"},
  {n:"Jigsaw Puzzles", r:"macro", icon:ICO+"jigsaw-puzzles.png", hero:null, y:"~1760"},
  // MICRO + MESO
  {n:"Super Smash Bros", r:"micro-meso", icon:ICO+"super-smash-bros.png", hero:null, y:"1999"},
  {n:"Street Fighter", r:"micro-meso", icon:ICO+"street-fighter.png", hero:null, y:"1987"},
  {n:"Tekken 8", r:"micro-meso", icon:ICO+"tekken-8.png", hero:null, y:"2024"},
  {n:"Mortal Kombat", r:"micro-meso", icon:ICO+"mortal-kombat.png", hero:null, y:"1992"},
  {n:"Guilty Gear", r:"micro-meso", icon:ICO+"guilty-gear.png", hero:null, y:"1998"},
  {n:"Dragon Ball FighterZ", r:"micro-meso", icon:ICO+"dragon-ball-fighterz.png", hero:null, y:"2018"},
  {n:"Brawlhalla", r:"micro-meso", icon:ICO+"brawlhalla.png", hero:null, y:"2017"},
  {n:"For Honor", r:"micro-meso", icon:ICO+"for-honor.png", hero:null, y:"2017"},
  {n:"Chivalry 2", r:"micro-meso", icon:ICO+"chivalry-2.png", hero:null, y:"2021"},
  {n:"Mordhau", r:"micro-meso", icon:ICO+"mordhau.png", hero:null, y:"2019"},
  {n:"Quake", r:"micro-meso", icon:ICO+"quake.png", hero:null, y:"1996"},
  {n:"Tetris 99", r:"micro-meso", icon:ICO+"tetris-99.png", hero:null, y:"2019"},
  {n:"Fall Guys", r:"micro-meso", icon:ICO+"fall-guys.png", hero:null, y:"2020"},
  {n:"Gang Beasts", r:"micro-meso", icon:ICO+"gang-beasts.png", hero:null, y:"2017"},
  {n:"Party Animals", r:"micro-meso", icon:ICO+"party-animals.png", hero:null, y:"2023"},
  {n:"Mario Kart", r:"micro-meso", icon:ICO+"mario-kart.png", hero:null, y:"1992"},
  {n:"2XKO", r:"micro-meso", icon:ICO+"2xko.png", hero:null, y:"2025"},
  // CENTER
  {n:"Counter-Strike 2", r:"center", icon:ICO+"counter-strike-2.png", hero:null, y:"2023"},
  {n:"Valorant", r:"center", icon:ICO+"valorant.png", hero:null, y:"2020"},
  {n:"League of Legends", r:"center", icon:ICO+"league-of-legends.png", hero:null, y:"2009"},
  {n:"Dota 2", r:"center", icon:ICO+"dota-2.png", hero:null, y:"2013"},
  {n:"Overwatch", r:"center", icon:ICO+"overwatch.png", hero:null, y:"2016"},
  {n:"Apex Legends", r:"center", icon:ICO+"apex-legends.png", hero:null, y:"2019"},
  {n:"Rocket League", r:"center", icon:ICO+"rocket-league.png", hero:null, y:"2015"},
  {n:"Fortnite", r:"center", icon:ICO+"fortnite.png", hero:null, y:"2017"},
  {n:"Rainbow Six Siege", r:"center", icon:ICO+"rainbow-six-siege.png", hero:null, y:"2015"},
  {n:"StarCraft II", r:"center", icon:ICO+"starcraft-ii.png", hero:null, y:"2010"},
  {n:"Halo Infinite", r:"center", icon:ICO+"halo-infinite.png", hero:null, y:"2021"},
  {n:"The Finals", r:"center", icon:ICO+"the-finals.png", hero:null, y:"2023"},
  {n:"PUBG", r:"center", icon:ICO+"pubg.png", hero:null, y:"2017"},
  {n:"Dead by Daylight", r:"center", icon:ICO+"dead-by-daylight.png", hero:null, y:"2016"},
  {n:"CoD Modern Warfare", r:"center", icon:ICO+"cod-modern-warfare.png", hero:null, y:"2019"},
  {n:"Marvel Rivals", r:"center", icon:ICO+"marvel-rivals.png", hero:null, y:"2024"},
  {n:"Team Fortress 2", r:"center", icon:ICO+"team-fortress-2.png", hero:null, y:"2007"},
  {n:"SMITE", r:"center", icon:ICO+"smite.png", hero:null, y:"2014"},
  {n:"Battlefield", r:"center", icon:ICO+"battlefield.png", hero:null, y:"2002"},
  {n:"Destiny 2", r:"center", icon:ICO+"destiny-2.png", hero:null, y:"2017"},
  {n:"Rust", r:"center", icon:ICO+"rust.png", hero:null, y:"2018"},
  {n:"Deadlock", r:"center", icon:ICO+"deadlock.png", hero:null, y:"2024"},
  {n:"Diablo IV", r:"center", icon:ICO+"diablo-iv.png", hero:null, y:"2023"},
  {n:"Naraka: Bladepoint", r:"center", icon:ICO+"naraka-bladepoint.png", hero:null, y:"2021"},
  {n:"Warframe", r:"center", icon:ICO+"warframe.png", hero:null, y:"2013"},
  {n:"World of Warcraft", r:"center", icon:ICO+"world-of-warcraft.png", hero:null, y:"2004"},
  {n:"Delta Force", r:"center", icon:ICO+"delta-force.png", hero:null, y:"2024"},
  {n:"ARC Raiders", r:"center", icon:ICO+"arc-raiders.png", hero:null, y:"2025"},
  {n:"EA Sports FC", r:"center", icon:ICO+"ea-sports-fc.png", hero:null, y:"2023"},
  {n:"Trackmania", r:"center", icon:ICO+"trackmania.png", hero:null, y:"2020"},
  {n:"Clash Royale", r:"center", icon:ICO+"clash-royale.png", hero:null, y:"2016"},
  {n:"Escape from Tarkov", r:"center", icon:ICO+"escape-from-tarkov.png", hero:null, y:"2017"},
  {n:"ARK: Survival Evolved", r:"center", icon:ICO+"ark.png", hero:null, y:"2017"},
  {n:"MCSR Ranked", r:"center", icon:ICO+"mcsr-ranked.png", hero:null, y:"2022"},
  // MESO + MACRO
  {n:"Hearthstone", r:"meso-macro", icon:ICO+"hearthstone.png", hero:null, y:"2014"},
  {n:"Teamfight Tactics", r:"meso-macro", icon:ICO+"teamfight-tactics.png", hero:null, y:"2019"},
  {n:"Balatro", r:"meso-macro", icon:ICO+"balatro.png", hero:null, y:"2024"},
  {n:"Slay the Spire 2", r:"meso-macro", icon:ICO+"slay-the-spire-2.png", hero:null, y:"2025"},
  {n:"Pokémon VGC", r:"meso-macro", icon:ICO+"pokemon-vgc.png", hero:null, y:"2008"},
  {n:"MTG Arena", r:"meso-macro", icon:ICO+"mtg-arena.png", hero:null, y:"2019"},
  {n:"Chess", r:"meso-macro", icon:ICO+"chess.png", hero:null, y:"~600"},
  {n:"Civilization VI", r:"meso-macro", icon:ICO+"civilization-vi.png", hero:null, y:"2016"},
  {n:"Poker", r:"meso-macro", icon:ICO+"poker.png", hero:null, y:"1800s"},
  {n:"Risk", r:"meso-macro", icon:ICO+"risk.png", hero:null, y:"1957"},
  {n:"Catan", r:"meso-macro", icon:ICO+"catan.png", hero:null, y:"1995"},
  {n:"Battleship", r:"meso-macro", icon:ICO+"battleship.png", hero:null, y:"1967"},
  {n:"Monopoly", r:"meso-macro", icon:ICO+"monopoly.png", hero:null, y:"1935"},
  {n:"Super Auto Pets", r:"meso-macro", icon:ICO+"super-auto-pets.png", hero:null, y:"2021"},
  {n:"Phasmophobia", r:"meso-macro", icon:ICO+"phasmophobia.png", hero:null, y:"2020"},
  // MESO
  {n:"Among Us", r:"meso", icon:ICO+"among-us.png", hero:null, y:"2018"},
  {n:"Goose Goose Duck", r:"meso", icon:ICO+"goose-goose-duck.png", hero:null, y:"2021"},
  {n:"Liar's Bar", r:"meso", icon:ICO+"liars-bar.png", hero:null, y:"2024"},
  {n:"Codenames", r:"meso", icon:ICO+"codenames.png", hero:null, y:"2015"},
  {n:"Rock Paper Scissors", r:"meso", icon:ICO+"rock-paper-scissors.png", hero:null, y:"antiquity"},
  {n:"SpyParty", r:"meso", icon:ICO+"spyparty.png", hero:null, y:"2018"},
  {n:"Secret Neighbor", r:"meso", icon:ICO+"secret-neighbor.png", hero:null, y:"2019"},
  {n:"Guess Who?", r:"meso", icon:ICO+"guess-who.png", hero:null, y:"1979"},
  {n:"GTA Online", r:"meso", icon:ICO+"gta-online.png", hero:null, y:"2013"},
  {n:"Werewolf Party", r:"meso", icon:ICO+"werewolf-party.png", hero:null, y:"1986"},
  {n:"The Stock Market", r:"meso", icon:ICO+"the-stock-market.png", hero:null, y:"1602"},
  {n:"Slot Machine", r:"meso", icon:ICO+"slot-machine.png", hero:null, y:"1895"},
  {n:"Town of Salem", r:"meso", icon:ICO+"town-of-salem.png", hero:null, y:"2014"},
  {n:"Blood on the Clocktower", r:"meso", icon:ICO+"blood-on-the-clocktower.png", hero:null, y:"2022"},
  {n:"Mafia", r:"meso", icon:ICO+"mafia.png", hero:null, y:"1986"},
  {n:"Coup", r:"meso", icon:ICO+"coup.png", hero:null, y:"2012"},
  {n:"The Resistance: Avalon", r:"meso", icon:ICO+"avalon.png", hero:null, y:"2012"},
  {n:"Spyfall", r:"meso", icon:ICO+"spyfall.png", hero:null, y:"2014"},
  {n:"Project Winter", r:"meso", icon:ICO+"project-winter.png", hero:null, y:"2019"},
  {n:"Liar's Dice", r:"meso", icon:ICO+"liars-dice.png", hero:null, y:"1800s"},
  {n:"Case Unboxing", r:"meso", icon:ICO+"case-unboxing.png", hero:null, y:"2013"},
];
const REGIONS = {
  "micro": "Micro",
  "micro-macro": "Micro + Macro",
  "macro": "Macro",
  "micro-meso": "Micro + Meso",
  "center": "Micro + Meso + Macro",
  "meso-macro": "Meso + Macro",
  "meso": "Meso",
};
